/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#FFFFFF",
        "canvas-global": "#FFFFFF",
        "canvas-primary": "#FFFFFF",
        "surface": "#FFFFFF",
        "surface-container": "#FAFAFA",
        "surface-container-low": "#FFFFFF",
        "surface-container-high": "#F4F4F5",
        "surface-container-highest": "#E4E4E7",
        "surface-container-lowest": "#FFFFFF",
        "surface-bright": "#FFFFFF",
        "surface-variant": "#F4F4F5",
        "surface-dim": "#FAFAFA",
        "panel-high": "#FFFFFF",
        "panel-low": "#FFFFFF",
        "border": "#E5E7EB",
        "border-structural": "#111111",
        "border-strong": "#111111",
        "border-internal": "#E5E7EB",
        "text": "#111111",
        "text-muted": "#666666",
        "on-surface": "#111111",
        "on-surface-variant": "#555555",
        "on-background": "#111111",
        "primary": "#F4C542",
        "primary-hover": "#E0B435",
        "primary-container": "#F4C542",
        "primary-fixed": "#F4C542",
        "primary-fixed-dim": "#F4C542",
        "interactive-primary": "#F4C542",
        "on-primary": "#111111",
        "on-primary-fixed": "#111111",
        "on-primary-fixed-variant": "#111111",
        "secondary": "#111111",
        "secondary-fixed": "#F4C542",
        "secondary-fixed-dim": "#F4C542",
        "secondary-container": "#F4F4F5",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#111111",
        "tertiary": "#111111",
        "outline": "#D1D5DB",
        "outline-variant": "#E5E7EB",
        "warning": "#F4C542",
        "success": "#111111",
        "error": "#111111",
        "error-container": "#FAFAFA",
        "on-error": "#FFFFFF",
        "on-error-container": "#111111",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "40px",
        "margin-safe": "32px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px",
        "gutter": "20px",
        "xs": "4px",
        "base": "4px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "h2": ["Manrope"],
        "mono-data": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Manrope"],
        "h4": ["Manrope"],
        "h1": ["Manrope"],
        sans: ['Inter', 'sans-serif'],
        heading: ['Manrope', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.05em", "fontWeight": "520" }],
        "mono-data": ["13px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "520" }],
        "h4": ["18px", { "lineHeight": "1.4", "letterSpacing": "-0.02em", "fontWeight": "520" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.05em", "fontWeight": "520" }]
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float-slow': 'floatSlow 8s ease-in-out infinite',
        'float-med': 'floatMed 6s ease-in-out infinite',
        'scale-in': 'scaleIn 0.2s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        floatSlow: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(-24px) scale(1.04)' },
        },
        floatMed: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(18px) scale(0.97)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
